CREATE DATABASE IF NOT EXISTS ESC_SFDC_TO_DB; 

CREATE TABLE IF NOT EXISTS ESC_SFDC_TO_DB.Account(
  Id VARCHAR(300) UNIQUE,
  Name VARCHAR(300),
  AccountNumber VARCHAR(300),
  OwnerId VARCHAR(300),
  NumberOfEmployees VARCHAR(300),
  Phone VARCHAR(300),
  Status VARCHAR(300)
);